# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Orthic Shorthand
tagline: Light letters, simple shortcuts
email: me@jeremywsherman.com
description: >- # this means to ignore newlines until "baseurl:"
  Double your handwriting speed with this no-nonsense shorthand system.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://orthic.shorthand.fun" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeremywsherman
github_username:  jeremy-w
permalink: "/:title"
timezone: "America/New_York"
encoding: "utf-8"

# Build settings
# Theme info:
#  https://www.csrhymes.com/development/2019/02/09/getting-started-with-bulma-clean-theme.html
# Source: https://github.com/chrisrhymes/bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/notes/page-:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
